---
# https://github.com/amannn/action-semantic-pull-request
# Validate the pull request title.

name: Semantic

on:
  pull_request_target:
    types: [opened, edited, reopened]
  workflow_call:

permissions:
  pull-requests: read

jobs:
  check-title-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
