---
# https://github.com/actions/stale
# Close stale issues and pull requests.

name: Stale

on:
  schedule:
    - cron: "0 7 * * *" # Run daily at 2 AM ET (07:00 UTC)
  workflow_call:
    inputs:
      days-before-stale:
        type: number
        default: 30
      days-before-close:
        type: number
        default: 7

env:
  days-before-stale: 30
  days-before-close: 7

permissions:
  actions: write
  issues: write
  pull-requests: write

jobs:
  check-issues-and-PRs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: ${{ inputs.days-before-stale || env.days-before-stale }}
          days-before-issue-close: ${{ inputs.days-before-close || env.days-before-close }}
          stale-issue-label: "stale(issue): inactive"
          stale-issue-message: |
            This issue has been automatically marked as stale due to inactivity.
            If this is still relevant, please comment or update the issue.
            It will be closed if no further activity occurs.
            Thank you for your contributions.
          close-issue-message: |
            Closing this issue after a prolonged period of inactivity.
            Please create a new issue with up-to-date information if needed.
            Thank you.
          days-before-pr-stale: ${{ inputs.days-before-stale || env.days-before-stale }}
          days-before-pr-close: ${{ inputs.days-before-close || env.days-before-close }}
          stale-pr-label: "stale(pull): inactive"
          stale-pr-message: |
            This pull request has been automatically marked as stale due to inactivity.
            If this is still relevant, please comment or remove the stale label.
            It will be closed if no further activity occurs.
            Thank you for your contributions.
          close-pr-message: |
            Closing this pull request after a prolonged period of inactivity.
            Please create a new pull request with up-to-date information if needed.
            Thank you.
          operations-per-run: 30
